// <auto-generated />
using System;
using LightingSystem.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LightingSystem.API.Migrations
{
    [DbContext(typeof(HomeLightSystemContext))]
    [Migration("20200208162651_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LightingSystem.Infrastructure.Database.Models.Bulb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Bulb");
                });

            modelBuilder.Entity("LightingSystem.Infrastructure.Database.Models.HomeLightSystem", b =>
                {
                    b.Property<Guid>("LocalLightingSystemId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserName");

                    b.HasKey("LocalLightingSystemId");

                    b.ToTable("HomeLightSystem");
                });

            modelBuilder.Entity("LightingSystem.Infrastructure.Database.Models.LightPoint", b =>
                {
                    b.Property<Guid>("LightPointId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("LocalLightingSystemId");

                    b.HasKey("LightPointId");

                    b.ToTable("LightPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
