// <auto-generated />
using System;
using LightingSystem.Data.EntityConfigurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LightingSystem.API.Migrations
{
    [DbContext(typeof(HomeLightSystemContext))]
    [Migration("20200222155557_ChangeInLightPoint4")]
    partial class ChangeInLightPoint4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LightingSystem.Domain.HomeLightSystem.HomeLightSystem", b =>
                {
                    b.Property<Guid>("LocalLightingSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("locallightingsystemid");

                    b.Property<string>("UserName");

                    b.HasKey("LocalLightingSystemId");

                    b.ToTable("homelightsystem");
                });

            modelBuilder.Entity("LightingSystem.Domain.HomeLightSystem.HomeLightSystem", b =>
                {
                    b.OwnsMany("LightingSystem.Domain.HomeLightSystem.LightPoint", "lightPoints", b1 =>
                        {
                            b1.Property<Guid>("LightPointId")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CustomName");

                            b1.Property<Guid>("HomeLightSystemLocalLightingSystemId");

                            b1.Property<bool>("IsAvailable");

                            b1.Property<string>("MqttId");

                            b1.HasKey("LightPointId");

                            b1.HasIndex("HomeLightSystemLocalLightingSystemId");

                            b1.ToTable("lightpoint");

                            b1.HasOne("LightingSystem.Domain.HomeLightSystem.HomeLightSystem")
                                .WithMany("lightPoints")
                                .HasForeignKey("HomeLightSystemLocalLightingSystemId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("LightingSystem.Domain.HomeLightSystem.Bulb", "lightBulbs", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<Guid>("LightPointId");

                                    b2.Property<int>("Number");

                                    b2.Property<bool>("Status");

                                    b2.HasKey("Id");

                                    b2.HasIndex("LightPointId");

                                    b2.ToTable("bulb");

                                    b2.HasOne("LightingSystem.Domain.HomeLightSystem.LightPoint")
                                        .WithMany("lightBulbs")
                                        .HasForeignKey("LightPointId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
