// <auto-generated />
using System;
using LightingSystem.Data.EntityConfigurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LightingSystem.API.Migrations
{
    [DbContext(typeof(HomeLightSystemContext))]
    [Migration("20200308111403_deleteFewProp")]
    partial class deleteFewProp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LightingSystem.Domain.HomeLightSystem.HomeLightSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("homelightsystem");
                });

            modelBuilder.Entity("LightingSystem.Domain.HomeLightSystem.HomeLightSystem", b =>
                {
                    b.OwnsMany("LightingSystem.Domain.HomeLightSystem.LightPoint", "lightPoints", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnName("id");

                            b1.Property<string>("CustomName");

                            b1.Property<Guid>("HomeLightSystemId")
                                .HasColumnName("homelightsystemid");

                            b1.Property<bool>("IsAvailable");

                            b1.Property<string>("MqttId");

                            b1.HasKey("Id");

                            b1.HasIndex("HomeLightSystemId");

                            b1.ToTable("lightpoint");

                            b1.HasOne("LightingSystem.Domain.HomeLightSystem.HomeLightSystem")
                                .WithMany("lightPoints")
                                .HasForeignKey("HomeLightSystemId")
                                .OnDelete(DeleteBehavior.Cascade);

                            b1.OwnsMany("LightingSystem.Domain.HomeLightSystem.LightBulb", "lightBulbs", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnName("id");

                                    b2.Property<Guid>("LightPointId")
                                        .HasColumnName("lightpointid");

                                    b2.Property<int>("Number");

                                    b2.Property<bool>("Status");

                                    b2.HasKey("Id");

                                    b2.HasIndex("LightPointId");

                                    b2.ToTable("lightbulb");

                                    b2.HasOne("LightingSystem.Domain.HomeLightSystem.LightPoint")
                                        .WithMany("lightBulbs")
                                        .HasForeignKey("LightPointId")
                                        .OnDelete(DeleteBehavior.Cascade);
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
